version: '2'

services:
  ubuntu:
    build:
      context: .
      dockerfile: docker/ubuntu/Dockerfile
    working_dir: /home/ubuntu/lihoubun
    volumes:
      - ".:/home/ubuntu/lihoubun"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    links:
      - mysql:mysql.local
    environment:
      ENV_SMTP_HOST: smtp.sendgrid.net
      ENV_SMTP_PORT: 587
      ENV_SMTP_USER: lihoubun
      ENV_SMTP_PASS: lihoubun
      LANG: ja_JP.UTF-8
      MYSQL_HOST: mysql.local
      MYSQL_DATABASE: lihoubun
      MYSQL_USER: lihoubun
      MYSQL_PASSWORD: lihoubun

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    volumes:
      - ".:/home/ubuntu/lihoubun"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: lihoubun
      MYSQL_USER: lihoubun
      MYSQL_PASSWORD: lihoubun
    expose:
      - "3306"
    ports:
      - "3306:3306"
  
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - ubuntu:ubuntu

volumes:
  mysql-data:
    driver: local