version: 2
jobs:
  build:
    working_directory: ~/project
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/php:7.1
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      - image: circleci/mysql:5.7.17
        environment:
          MYSQL_DATABASE: liho
          MYSQL_USER: liho
          MYSQL_PASSWORD: liho
    steps:
      - checkout
      - run: pwd
      - run: php -v
      - run: php ./composer.phar self-update
      - run: php ./composer.phar install
      - run: php oil r install
      - run: php oil test --group=Playground

  test:
    docker:
      - image: circleci/php:7.1
      - image: circleci/mysql:5.7.17
    steps:
      - checkout
      - run:
          name: Test
          command: php oil r install
          command: php oil r migrate

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /v*/
