version: 2
jobs:
  build:
    working_directory: $CIRCLE_WORKING_DIRECTORY
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run: 
          name: Check ENV
          command: |
            uname -a
            env
            pwd
            ls
      - run:
          name: Check Docker
          command: |
            docker version
            docker-compose version
      - run:
          name: Build CLI
          command: ./help.sh build