version: 2
jobs:
  build:
    working_directory: ~/project
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/php:7.1
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      - image: circleci/mysql:5.7.17
        environment:
          MYSQL_DATABASE: liho
          MYSQL_USER: liho
          MYSQL_PASSWORD: liho
    steps:
      - checkout
      # API-V1
      - run:
          name: Init api-v1
          pwd: ./api-v1/fuel
          command: |
            php ./composer.phar install
            php oil r install
            php oil r migrate
      - run:
          name: Test api-v1
          command: |
            php ./api-v1/fuel/oil test --group=Public
      # PHP Exercism
      - run:
          name: Init PHP Exercism
          pwd: ./php
          command: |
            sudo apt-get install -y wget
            ./install_composer.sh
            php ./composer.phar install
      - run:
          name: Test PHP Exercism
          pwd: ./php
          command: |
            ./vendor/phpunit/phpunit/phpunit  hello-world/hello-world_test.php

  test:
    docker:
      - image: circleci/php:7.1
      - image: circleci/mysql:5.7.17
    steps:
      - checkout
      - run:
          name: Test
          command: php oil r install
          command: php oil r migrate

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /v*/
