version: 2
jobs:
  build:
    working_directory: $CIRCLE_WORKING_DIRECTORY
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run: 
          name: Check ENV
          command: |
            uname -a
            env
            pwd
            ls -all
      - run:
          name: Check Docker
          command: |
            docker version
            docker-compose version
      - run:
          name: Build CLI
          command: |
            sh ./help.sh build
            sh ./help.sh up
      - run:
          name: Get API started
          command: |
            sh ./help.sh init
            sh ./help.sh migrate
            sh ./help.sh sql
            sh ./help.sh restore
            sh ./help.sh php --version
      - run:
          name: Test CLI
          command: |
            sh ./help.sh test